// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDD0JquYntFYutHh-9IxRQXmkXb32jdliA',
    appId: '1:76992454549:android:94e8525974972a6533609c',
    messagingSenderId: '76992454549',
    projectId: 'acofood-app',
    storageBucket: 'acofood-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0fM9EgfXmuAED_zbxrZjguHBn83D_U5c',
    appId: '1:76992454549:ios:45417d88d9ac272533609c',
    messagingSenderId: '76992454549',
    projectId: 'acofood-app',
    storageBucket: 'acofood-app.firebasestorage.app',
    iosClientId: '76992454549-mq2t4352o1tsr1bltu0rn43sui0a9fp1.apps.googleusercontent.com',
    iosBundleId: 'com.example.acofood2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0fM9EgfXmuAED_zbxrZjguHBn83D_U5c',
    appId: '1:76992454549:ios:45417d88d9ac272533609c',
    messagingSenderId: '76992454549',
    projectId: 'acofood-app',
    storageBucket: 'acofood-app.firebasestorage.app',
    iosClientId: '76992454549-mq2t4352o1tsr1bltu0rn43sui0a9fp1.apps.googleusercontent.com',
    iosBundleId: 'com.example.acofood2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAZOa_G9823IkxWawnOPjG4mm_J0yBEnc',
    appId: '1:76992454549:web:97e3eea4fcce150f33609c',
    messagingSenderId: '76992454549',
    projectId: 'acofood-app',
    authDomain: 'acofood-app.firebaseapp.com',
    storageBucket: 'acofood-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAZOa_G9823IkxWawnOPjG4mm_J0yBEnc',
    appId: '1:76992454549:web:97e3eea4fcce150f33609c',
    messagingSenderId: '76992454549',
    projectId: 'acofood-app',
    authDomain: 'acofood-app.firebaseapp.com',
    storageBucket: 'acofood-app.firebasestorage.app',
  );

}