import '../data/nutrient_goals.dart';

class NutrientInfo {
  final String key;
  final String displayName;
  final String unit;
  final double rdaValue;
  final String type; // RDA, AI, Meta, Límite

  const NutrientInfo({
    required this.key,
    required this.displayName,
    required this.unit,
    required this.rdaValue,
    required this.type,
  });
}

// Lista de nutrientes disponibles para análisis (excluye macros principales)
final List<NutrientInfo> availableNutrients = [
  // Fibra y grasas
  NutrientInfo(
    key: 'fiber',
    displayName: 'Fibra',
    unit: nutrientGoals['fiber']!['unit'],
    rdaValue: nutrientGoals['fiber']!['value'],
    type: nutrientGoals['fiber']!['type'],
  ),
  NutrientInfo(
    key: 'saturatedFats',
    displayName: 'Grasas Saturadas',
    unit: nutrientGoals['saturatedFats']!['unit'],
    rdaValue: nutrientGoals['saturatedFats']!['value'],
    type: nutrientGoals['saturatedFats']!['type'],
  ),
  NutrientInfo(
    key: 'omega3',
    displayName: 'Omega-3',
    unit: nutrientGoals['omega3']!['unit'],
    rdaValue: nutrientGoals['omega3']!['value'],
    type: nutrientGoals['omega3']!['type'],
  ),
  NutrientInfo(
    key: 'omega6',
    displayName: 'Omega-6',
    unit: nutrientGoals['omega6']!['unit'],
    rdaValue: nutrientGoals['omega6']!['value'],
    type: nutrientGoals['omega6']!['type'],
  ),
  NutrientInfo(
    key: 'omega9',
    displayName: 'Omega-9',
    unit: 'g',
    rdaValue: 0,
    type: 'N/A',
  ),

  // Minerales
  NutrientInfo(
    key: 'calcium',
    displayName: 'Calcio',
    unit: nutrientGoals['calcium']!['unit'],
    rdaValue: nutrientGoals['calcium']!['value'],
    type: nutrientGoals['calcium']!['type'],
  ),
  NutrientInfo(
    key: 'iron',
    displayName: 'Hierro',
    unit: nutrientGoals['iron']!['unit'],
    rdaValue: nutrientGoals['iron']!['value'],
    type: nutrientGoals['iron']!['type'],
  ),
  NutrientInfo(
    key: 'magnesium',
    displayName: 'Magnesio',
    unit: nutrientGoals['magnesium']!['unit'],
    rdaValue: nutrientGoals['magnesium']!['value'],
    type: nutrientGoals['magnesium']!['type'],
  ),
  NutrientInfo(
    key: 'phosphorus',
    displayName: 'Fósforo',
    unit: nutrientGoals['phosphorus']!['unit'],
    rdaValue: nutrientGoals['phosphorus']!['value'],
    type: nutrientGoals['phosphorus']!['type'],
  ),
  NutrientInfo(
    key: 'potassium',
    displayName: 'Potasio',
    unit: nutrientGoals['potassium']!['unit'],
    rdaValue: nutrientGoals['potassium']!['value'],
    type: nutrientGoals['potassium']!['type'],
  ),
  NutrientInfo(
    key: 'sodium',
    displayName: 'Sodio',
    unit: nutrientGoals['sodium']!['unit'],
    rdaValue: nutrientGoals['sodium']!['value'],
    type: nutrientGoals['sodium']!['type'],
  ),
  NutrientInfo(
    key: 'zinc',
    displayName: 'Zinc',
    unit: nutrientGoals['zinc']!['unit'],
    rdaValue: nutrientGoals['zinc']!['value'],
    type: nutrientGoals['zinc']!['type'],
  ),
  NutrientInfo(
    key: 'copper',
    displayName: 'Cobre',
    unit: nutrientGoals['copper']!['unit'],
    rdaValue: nutrientGoals['copper']!['value'],
    type: nutrientGoals['copper']!['type'],
  ),
  NutrientInfo(
    key: 'manganese',
    displayName: 'Manganeso',
    unit: nutrientGoals['manganese']!['unit'],
    rdaValue: nutrientGoals['manganese']!['value'],
    type: nutrientGoals['manganese']!['type'],
  ),
  NutrientInfo(
    key: 'selenium',
    displayName: 'Selenio',
    unit: nutrientGoals['selenium']!['unit'],
    rdaValue: nutrientGoals['selenium']!['value'],
    type: nutrientGoals['selenium']!['type'],
  ),
  NutrientInfo(
    key: 'iodine',
    displayName: 'Yodo',
    unit: nutrientGoals['iodine']!['unit'],
    rdaValue: nutrientGoals['iodine']!['value'],
    type: nutrientGoals['iodine']!['type'],
  ),
  NutrientInfo(
    key: 'molybdenum',
    displayName: 'Molibdeno',
    unit: nutrientGoals['molybdenum']!['unit'],
    rdaValue: nutrientGoals['molybdenum']!['value'],
    type: nutrientGoals['molybdenum']!['type'],
  ),
  NutrientInfo(
    key: 'chromium',
    displayName: 'Cromo',
    unit: nutrientGoals['chromium']!['unit'],
    rdaValue: nutrientGoals['chromium']!['value'],
    type: nutrientGoals['chromium']!['type'],
  ),
  NutrientInfo(
    key: 'fluorine',
    displayName: 'Flúor',
    unit: nutrientGoals['fluorine']!['unit'],
    rdaValue: nutrientGoals['fluorine']!['value'],
    type: nutrientGoals['fluorine']!['type'],
  ),

  // Vitaminas
  NutrientInfo(
    key: 'vitaminA',
    displayName: 'Vitamina A',
    unit: nutrientGoals['vitaminA']!['unit'],
    rdaValue: nutrientGoals['vitaminA']!['value'],
    type: nutrientGoals['vitaminA']!['type'],
  ),
  NutrientInfo(
    key: 'vitaminC',
    displayName: 'Vitamina C',
    unit: nutrientGoals['vitaminC']!['unit'],
    rdaValue: nutrientGoals['vitaminC']!['value'],
    type: nutrientGoals['vitaminC']!['type'],
  ),
  NutrientInfo(
    key: 'vitaminD',
    displayName: 'Vitamina D',
    unit: nutrientGoals['vitaminD']!['unit'],
    rdaValue: nutrientGoals['vitaminD']!['value'],
    type: nutrientGoals['vitaminD']!['type'],
  ),
  NutrientInfo(
    key: 'vitaminE',
    displayName: 'Vitamina E',
    unit: nutrientGoals['vitaminE']!['unit'],
    rdaValue: nutrientGoals['vitaminE']!['value'],
    type: nutrientGoals['vitaminE']!['type'],
  ),
  NutrientInfo(
    key: 'vitaminK',
    displayName: 'Vitamina K',
    unit: nutrientGoals['vitaminK']!['unit'],
    rdaValue: nutrientGoals['vitaminK']!['value'],
    type: nutrientGoals['vitaminK']!['type'],
  ),
  NutrientInfo(
    key: 'vitaminB1',
    displayName: 'Vitamina B1 (Tiamina)',
    unit: nutrientGoals['vitaminB1']!['unit'],
    rdaValue: nutrientGoals['vitaminB1']!['value'],
    type: nutrientGoals['vitaminB1']!['type'],
  ),
  NutrientInfo(
    key: 'vitaminB2',
    displayName: 'Vitamina B2 (Riboflavina)',
    unit: nutrientGoals['vitaminB2']!['unit'],
    rdaValue: nutrientGoals['vitaminB2']!['value'],
    type: nutrientGoals['vitaminB2']!['type'],
  ),
  NutrientInfo(
    key: 'vitaminB3',
    displayName: 'Vitamina B3 (Niacina)',
    unit: nutrientGoals['vitaminB3']!['unit'],
    rdaValue: nutrientGoals['vitaminB3']!['value'],
    type: nutrientGoals['vitaminB3']!['type'],
  ),
  NutrientInfo(
    key: 'vitaminB4',
    displayName: 'Vitamina B4 (Colina)',
    unit: nutrientGoals['vitaminB4']!['unit'],
    rdaValue: nutrientGoals['vitaminB4']!['value'],
    type: nutrientGoals['vitaminB4']!['type'],
  ),
  NutrientInfo(
    key: 'vitaminB5',
    displayName: 'Vitamina B5 (Ác. Pantoténico)',
    unit: nutrientGoals['vitaminB5']!['unit'],
    rdaValue: nutrientGoals['vitaminB5']!['value'],
    type: nutrientGoals['vitaminB5']!['type'],
  ),
  NutrientInfo(
    key: 'vitaminB6',
    displayName: 'Vitamina B6 (Piridoxina)',
    unit: nutrientGoals['vitaminB6']!['unit'],
    rdaValue: nutrientGoals['vitaminB6']!['value'],
    type: nutrientGoals['vitaminB6']!['type'],
  ),
  NutrientInfo(
    key: 'vitaminB7',
    displayName: 'Vitamina B7 (Biotina)',
    unit: nutrientGoals['vitaminB7']!['unit'],
    rdaValue: nutrientGoals['vitaminB7']!['value'],
    type: nutrientGoals['vitaminB7']!['type'],
  ),
  NutrientInfo(
    key: 'vitaminB9',
    displayName: 'Vitamina B9 (Ácido Fólico)',
    unit: nutrientGoals['vitaminB9']!['unit'],
    rdaValue: nutrientGoals['vitaminB9']!['value'],
    type: nutrientGoals['vitaminB9']!['type'],
  ),
  NutrientInfo(
    key: 'vitaminB12',
    displayName: 'Vitamina B12 (Cobalamina)',
    unit: nutrientGoals['vitaminB12']!['unit'],
    rdaValue: nutrientGoals['vitaminB12']!['value'],
    type: nutrientGoals['vitaminB12']!['type'],
  ),

  // Aminoácidos esenciales
  NutrientInfo(
    key: 'histidine',
    displayName: 'Histidina',
    unit: nutrientGoals['histidine']!['unit'],
    rdaValue: nutrientGoals['histidine']!['value'],
    type: nutrientGoals['histidine']!['type'],
  ),
  NutrientInfo(
    key: 'isoleucine',
    displayName: 'Isoleucina',
    unit: nutrientGoals['isoleucine']!['unit'],
    rdaValue: nutrientGoals['isoleucine']!['value'],
    type: nutrientGoals['isoleucine']!['type'],
  ),
  NutrientInfo(
    key: 'leucine',
    displayName: 'Leucina',
    unit: nutrientGoals['leucine']!['unit'],
    rdaValue: nutrientGoals['leucine']!['value'],
    type: nutrientGoals['leucine']!['type'],
  ),
  NutrientInfo(
    key: 'lysine',
    displayName: 'Lisina',
    unit: nutrientGoals['lysine']!['unit'],
    rdaValue: nutrientGoals['lysine']!['value'],
    type: nutrientGoals['lysine']!['type'],
  ),
  NutrientInfo(
    key: 'methionine',
    displayName: 'Metionina',
    unit: nutrientGoals['methionine']!['unit'],
    rdaValue: nutrientGoals['methionine']!['value'],
    type: nutrientGoals['methionine']!['type'],
  ),
  NutrientInfo(
    key: 'phenylalanine',
    displayName: 'Fenilalanina',
    unit: nutrientGoals['phenylalanine']!['unit'],
    rdaValue: nutrientGoals['phenylalanine']!['value'],
    type: nutrientGoals['phenylalanine']!['type'],
  ),
  NutrientInfo(
    key: 'threonine',
    displayName: 'Treonina',
    unit: nutrientGoals['threonine']!['unit'],
    rdaValue: nutrientGoals['threonine']!['value'],
    type: nutrientGoals['threonine']!['type'],
  ),
  NutrientInfo(
    key: 'tryptophan',
    displayName: 'Triptófano',
    unit: nutrientGoals['tryptophan']!['unit'],
    rdaValue: nutrientGoals['tryptophan']!['value'],
    type: nutrientGoals['tryptophan']!['type'],
  ),
  NutrientInfo(
    key: 'valine',
    displayName: 'Valina',
    unit: nutrientGoals['valine']!['unit'],
    rdaValue: nutrientGoals['valine']!['value'],
    type: nutrientGoals['valine']!['type'],
  ),

  // Aminoácidos no esenciales (sin RDA)
  NutrientInfo(
    key: 'alanine',
    displayName: 'Alanina',
    unit: 'mg',
    rdaValue: 0,
    type: 'N/A',
  ),
  NutrientInfo(
    key: 'arginine',
    displayName: 'Arginina',
    unit: 'mg',
    rdaValue: 0,
    type: 'N/A',
  ),
  NutrientInfo(
    key: 'asparticAcid',
    displayName: 'Ácido Aspártico',
    unit: 'mg',
    rdaValue: 0,
    type: 'N/A',
  ),
  NutrientInfo(
    key: 'glutamicAcid',
    displayName: 'Ácido Glutámico',
    unit: 'mg',
    rdaValue: 0,
    type: 'N/A',
  ),
  NutrientInfo(
    key: 'glycine',
    displayName: 'Glicina',
    unit: 'mg',
    rdaValue: 0,
    type: 'N/A',
  ),
  NutrientInfo(
    key: 'proline',
    displayName: 'Prolina',
    unit: 'mg',
    rdaValue: 0,
    type: 'N/A',
  ),
  NutrientInfo(
    key: 'serine',
    displayName: 'Serina',
    unit: 'mg',
    rdaValue: 0,
    type: 'N/A',
  ),
  NutrientInfo(
    key: 'tyrosine',
    displayName: 'Tirosina',
    unit: 'mg',
    rdaValue: 0,
    type: 'N/A',
  ),
  NutrientInfo(
    key: 'cysteine',
    displayName: 'Cisteína',
    unit: 'mg',
    rdaValue: 0,
    type: 'N/A',
  ),
  NutrientInfo(
    key: 'glutamine',
    displayName: 'Glutamina',
    unit: 'mg',
    rdaValue: 0,
    type: 'N/A',
  ),
  NutrientInfo(
    key: 'asparagine',
    displayName: 'Asparagina',
    unit: 'mg',
    rdaValue: 0,
    type: 'N/A',
  ),
];
